# Generated by Django 3.0.8 on 2020-12-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(blank=True, max_length=122, null=True)),
                ('emp_email', models.CharField(blank=True, max_length=122, null=True)),
                ('country', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/images')),
            ],
        ),
    ]
